apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::119997536442:role/eksctl-safe-button-addon-iamserviceaccount-ku-Role1-dmOrV83TPW6k
